### ISSUE TITLE
Completed Extension :)

### ISSUE THREAD

**Issue by nitsan-technologies** [NetConsultAG/netc_nsb#1]
Hi @angeloprevitali 

We have completed our extension with testing. 

**Uploaded work:** Find here our latest work > https://github.com/NetConsultAG/netc_nsb

**QA Test cases:** We have prepare some test cases while testing this extension. We will send it in mail in few mins.

....

Please share your input now. Thanks!

**Comment by angeloprevitali** [comment]
We installed the EXT:netc_nsb on the dev server. We installed it for showing a single item (message). The message is displayed correctly but there is an error on the page. See printscreen.
![screenshot-2016-07-11-11-30-45](https://cloud.githubusercontent.com/assets/17588253/16726136/f9b77d7e-475a-11e6-8afe-34104aadd2d5.png)

**Comment by nitsan-technologies** [comment]
Above issue is fix > http://prntscr.com/brx57e ( this is our local test server )

We have resolved all issues & uploaded our latest work here > https://github.com/NetConsultAG/netc_nsb

**Comment by angeloprevitali** [comment]
OK.
