### ISSUE TITLE
List of messages is not shown for EN, FR, IT

### ISSUE THREAD

**Issue by ernestpeter** [NetConsultAG/netc_nsb#10]
We gett error message 
Fatal error: Call to a member function getOrgId() on null in /home/httpd/vhosts/netconsult.ch/dev.kommission.netconsult.ch/typo3conf/ext/netc_nsb/Classes/Controller/OrganisationsController.php on line 77
see http://dev.kommission.netconsult.ch/en/themen-en/uebersicht-en/medienmitteilungen-comcom-en/

**Comment by nitsan-technologies** [comment]
Hi,

This is also solved. Please check FR - http://prntscr.com/bv4e6j, IT - http://prntscr.com/bv4eg4, EN - http://prntscr.com/bv4ekq

Thanks!

**Comment by ernestpeter** [comment]
Still does not work for empty start and end date (see http://kommission.netconsult.ch/index.php?id=192&L=3 for English)

**Comment by angeloprevitali** [comment]
Remark: Please keep for standard usage of TYPO3 CMS the language parameter of the item of configuration file always in [Default] language. Please adapt this for this EXT. Thanks.

http://prntscr.com/c1jc83

**Comment by nitsan-technologies** [comment]
Hi, 

Both issues solved. Please check detail below.

https://github.com/NetConsultAG/netc_nsb/issues/10
Still does not work for empty start and end date (see http://kommission.netconsult.ch/index.php?id=192&L=3 for English)
**Status >** It seems there is some other problem. Its dont related with EXT:netc_nsb. We have check without start and end date at http://dev.kommission.netconsult.ch/fr/themen-fr/uebersicht-fr/. Please check screen-shots http://prntscr.com/c29471,http://prntscr.com/c298rp  it is working there.

.....

Remark: Please keep for standard usage of TYPO3 CMS the language parameter of the item of configuration file always in [Default] language. Please adapt this for this EXT. Thanks.

http://prntscr.com/c1jc83
**Status >** Done. 

**Note :** We have now used Typo3 Default language as per you said. Please check we use this http://prntscr.com/c299zz. We have removed language selection http://prntscr.com/c29a91 from flexfrom (Plugin configuration) as we now used Typo3 current language.

**Comment by ernestpeter** [comment]
I still get error:
Fatal error: Call to a member function getOrgId() on null in /home/httpd/vhosts/netconsult.ch/dev.kommission.netconsult.ch/typo3conf/ext/netc_nsb/Classes/Controller/OrganisationsController.php on line 84
in http://dev.kommission.netconsult.ch/index.php?id=181&L=3
Please install and test also on dev.kommission.netconsult.ch

**Comment by nitsan-technologies** [comment]
Hi,

Please check it now http://dev.kommission.netconsult.ch/index.php?id=181&L=3.

Please use latest code from and try 

Thanks!

**Comment by ernestpeter** [comment]
Get an error when setting flag for leads:
PHP Warning: preg_split() expects parameter 2 to be string, array given in /home/httpd/vhosts/netconsult.ch/dev.kommission.netconsult.ch/typo3/sysext/core/Classes/Html/HtmlParser.php line 325
see 
http://dev.kommission.netconsult.ch/index.php?id=181&L=3

**Comment by nitsan-technologies** [comment]
Hi,

There is some problem with your Typo3 configuration for english language.
Our extension works okay with that leads flag. You can check it here http://dev.kommission.netconsult.ch/fr/themen-fr/uebersicht-fr/medienmitteilungen-comcom-fr/ for french language 

Thanks!

**Comment by angeloprevitali** [comment]
Hi

We got NO TYPO3 configuration error on EN pages.

BUT if we call up the page in developer modus (install tool > Configuration presets > Development) you will see an error on EN version, ONLY. By DISABLING this modus NO error appears. 

Try it on your envoirement and let me know.

We will DISABLE this modus after going live for shure with the EXT:netc_nsb, but I would suggest to check again this error due to it appears only on EN language and it seems to me that it SHOULD not come in no way.

Please advice.

Thanks.

Regards,
Angelo

**Comment by nitsan-technologies** [comment]
Hi,

We have found issue. There was problem in feed data. As it return blank description. Please check http://prntscr.com/c3wlpi, http://prntscr.com/c3wlu2

Which causes problem in fetch description. it fetched as array. So it was generating error. We have set condition for it. 

Please check it at your end with latest code.

Thanks!

**Comment by ernestpeter** [comment]
Sorry, still get error message:
Fatal error: Call to a member function getOrgId() on null in /home/httpd/vhosts/netconsult.ch/kommission.netconsult.ch/typo3conf/ext/netc_nsb/Classes/Controller/OrganisationsController.php on line 84
when trying a list af messages in FR, IT, EN on http://kommission.netconsult.ch
in pages 192 and 200

**Comment by nitsan-technologies** [comment]
Hi,

Everything works okay at http://dev.kommission.netconsult.ch. 
Please check http://dev.kommission.netconsult.ch/de/themen/uebersicht/, http://dev.kommission.netconsult.ch/fr/themen-fr/uebersicht-fr/, http://dev.kommission.netconsult.ch/it/themen-it/uebersicht-it/, http://dev.kommission.netconsult.ch/en/themen-en/uebersicht-en/

As you said to test here http://kommission.netconsult.ch. We didn't have access to this site. Please send credential in mail.

Thanks!

**Comment by ernestpeter** [comment]
Credential was sent on Monday

**Comment by nitsan-technologies** [comment]
Hi,

Have you send Credential in mail?

We have tried to check in mail/Skype but not found, So please share it again. Thanks!

**Comment by ernestpeter** [comment]
Hi Sanjay
I sent the credentials again to sanjay@nitsan.in.
Kind regards, Ernest

**Comment by nitsan-technologies** [comment]
Hi,

It is working okay. Please check http://prntscr.com/ceb77z, http://prntscr.com/ceba1g, http://prntscr.com/ceba6m, http://prntscr.com/cebbd0, http://prntscr.com/cebbhl

Also check following links :
http://kommission.netconsult.ch/de/themen/medienmitteilungen-comcom/
http://kommission.netconsult.ch/en/themen-en/media-news-comcom/

http://kommission.netconsult.ch/index.php?id=200
http://kommission.netconsult.ch/fr/dokumentation/apercu/medienmitteilungen-liste-fr/

Although please let me know if you have any queries.

Thanks!

**Comment by michelrossier** [comment]
Hi 
Thank you! What did you had to do in order to make it work again? I've seen there haven't been any commits on the source code on Github. Was it just a configuration change, if yes, which? Thank you!

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

We haven't made any change in configuration either. We have just login with your given credential and clear Cache. That's it. We haven't made any changes.

Thanks!

**Comment by michelrossier** [comment]
Hi @nitsan-technologies 
Thanks for your feedback. Okay, then everything is okay for us and we will initiate the payment asap.
