### ISSUE TITLE
CR: additional field "Lead" in backend for function "Display a list of all news messages"

### ISSUE THREAD

**Issue by ernestpeter** [NetConsultAG/netc_nsb#11]
The editor should see an additional field "Display Lead" in the backend.
Ticking the field should include the Leads in the list am messages like in example 
https://www.admin.ch/gov/en/start/documentation/media-releases.html
(but without the search filter).

Please tell us, if this is included in the offered price or if not, how much this additional feature will cost.

**Comment by nitsan-technologies** [comment]
Hi,

Please confirm following : 

As per you said, The editor can tick the field 'Display lead' in BE which will be implement here http://prntscr.com/bv8pu9. 

When editor tick the checkbox 'Display lead', We will show lead(description attribute from RSS http://prntscr.com/bv8r35, http://prntscr.com/bv8scv) here in FE http://prntscr.com/bv8sld as http://prntscr.com/bv8srj

Is it right? Please confirm the requirement, so we can give you exact hours.

**Comment by ernestpeter** [comment]
The editor can tick the field 'Display lead' in BE which will be implement here http://prntscr.com/bv8pu9.
**yes**
When editor tick the checkbox 'Display lead', We will show lead(description attribute from RSS http://prntscr.com/bv8r35, http://prntscr.com/bv8scv
**yes. The required lead field ist called "description".**

here in FE http://prntscr.com/bv8sld as http://prntscr.com/bv8srj
**exactly**

**Comment by nitsan-technologies** [comment]
Okay,
We will need around 1 hour for implement this and testing. Please confirm this so we can start work on it.

**Comment by ernestpeter** [comment]
I confirm, that you can start work.
Kind regards
Ernest

**Comment by nitsan-technologies** [comment]
Hi,

This task has been done.

**Note :** We have given option for editor to tick for description http://prntscr.com/by1649, http://prntscr.com/by1679

Thanks!

**Comment by ernestpeter** [comment]
Well done, thank you.
