### ISSUE TITLE
Debugmodus still active?

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_nsb#3]
By calling up a page in list view there is the fetched url coming in the top of the page.
![screenshot-2016-07-11-15-33-28](https://cloud.githubusercontent.com/assets/17588253/16732346/fafad646-477c-11e6-82d9-61fd280eeadd.png)

**Comment by nitsan-technologies** [comment]
We have fixed this > http://prntscr.com/brwov7 , http://prntscr.com/brwp2w

**Comment by angeloprevitali** [comment]
That's ok.
