### ISSUE TITLE
Begin and end date not properly working

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_nsb#4]
By adding a from date ther should come all news until the actual date. If you choose a date until date every item should come and be displayed until this date.

**Comment by nitsan-technologies** [comment]
We have fixed this:

Start Date:
Without Date: BE > http://prntscr.com/brwtt0 , FE > http://prntscr.com/brwu17
After 01-01-2015 : BE > http://prntscr.com/brwuxp , FE > http://prntscr.com/brwuo2
After 01-01-2016 : BE > http://prntscr.com/brwv4z , FE > http://prntscr.com/brwvmi
After 24-05-2016 : BE > http://prntscr.com/brww6d , FE > http://prntscr.com/brwwal

Start Date to End Date:
Without Date: BE > http://prntscr.com/brwxbw , FE > http://prntscr.com/brwx4l
20-03-2009 to 31-12-2009 : BE > http://prntscr.com/brwyxj , FE > http://prntscr.com/brwza8
13-06-2016 to 30-07-2016 : BE > http://prntscr.com/brx0ay , FE > http://prntscr.com/brx0g8

End Date:
Without Date: BE > http://prntscr.com/brx17i , FE: http://prntscr.com/brx1bm
Befor 16-05-2008 : BE > http://prntscr.com/brx2mu , FE > http://prntscr.com/brx2rd
Befor 17-05-2002 : BE > http://prntscr.com/brx3db , FE > http://prntscr.com/brx3k8 
Befor 08-02-2001 : BE > http://prntscr.com/brx3ud , FE > http://prntscr.com/brx421

**Comment by angeloprevitali** [comment]
Ok.
