### ISSUE TITLE
Detail page

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_nsb#5]
On the detail page (news details from listing) there is the fetched url coming in hte header of the page.
![screenshot-2016-07-11-15-40-22](https://cloud.githubusercontent.com/assets/17588253/16732511/e6149662-477d-11e6-8623-28bd83c1833e.png)

**Comment by nitsan-technologies** [comment]
Done > http://prntscr.com/brx57e

**Comment by angeloprevitali** [comment]
OK.
