### ISSUE TITLE
Missing element in footer area as described in specs

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_nsb#6]
The documents in the footer area which comes with a RSSS feed aren't still integrated yet. Example link like it should be displayed: https://www.admin.ch/gov/en/start/documentation/media-releases/media-releases-federal-council.msg-id-61668.html 
![screenshot-2016-07-14-09-03-27](https://cloud.githubusercontent.com/assets/17588253/16830971/7ee6c7fe-49a2-11e6-8b67-a9376066b5b8.png)

**Comment by nitsan-technologies** [comment]
Hi, 

We have uploaded latest code. http://prntscr.com/bt7u5d

**Comment by nitsan-technologies** [comment]
Hi,

It is done. Please check http://prntscr.com/bvo15c , http://prntscr.com/bvo2o3 , http://prntscr.com/bvo2w9

**Note :** Please read my comment on https://github.com/NetConsultAG/netc_nsb/issues/8

Thanks!

**Comment by nitsan-technologies** [comment]
Hi,

Please check my comment at #8 

Thanks!
