### ISSUE TITLE
Missing minus sign between Publication date and Lead

### ISSUE THREAD

**Issue by ernestpeter** [NetConsultAG/netc_nsb#7]
There should be a minus sign between Publication date and Lead.
For message Nr. 62640 this should be 
Bern, 12.07.2016 - Zwischen …
and not Bern, 12.07.2016 Zwischen …

**Comment by nitsan-technologies** [comment]
Hi,

This is solved. Please check http://prntscr.com/bvo3wi , http://prntscr.com/bvo451

Thanks!

**Comment by ernestpeter** [comment]
Confirmed. Thank you.
